
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from backend import Main

# add_to_product = Main().add_product()

class AddProduct:
    def __init__(self):
        self.OUTPUT_PATH = Path(__file__).parent
        self.ASSETS_PATH = self.OUTPUT_PATH / Path(r"C:\Users\Martin\Desktop\Database\assets\frame1")


    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

    def run(self, win):
        window = win

        window.geometry("340x410")
        window.configure(bg = "#141A29")


        canvas = Canvas(
            window,
            bg = "#141A29",
            height = 410,
            width = 340,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            master=canvas,
            name="img2",
            file=self.relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            170.0,
            233.0,
            image=image_image_1
        )

        canvas.create_text(
            13.0,
            20.0,
            anchor="nw",
            text="Add A Product",
            fill="#FFFFFF",
            font=("YanoneKaffeesatz Regular", 20 * -1)
        )

        entry_image_1 = PhotoImage(
            master=canvas,
            name="ent1",
            file=self.relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            165.5,
            127.0,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#999B9F",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=24.0,
            y=106.0,
            width=285.0,
            height=40.0
        )

        canvas.create_text(
            26.0,
            80.0,
            anchor="nw",
            text="Name Of The Product: ",
            fill="#000000",
            font=("YanoneKaffeesatz Regular", 17 * -1)
        )

        entry_image_2 = PhotoImage(
            master=canvas,
            name="ent2",
            file=self.relative_to_assets("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            165.5,
            203.5,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#989A9E",
            fg="#000716",
            highlightthickness=0
        )
        entry_2.place(
            x=24.0,
            y=183.0,
            width=285.0,
            height=40.0
        )

        canvas.create_text(
            26.0,
            159.0,
            anchor="nw",
            text="Store Date Of The Product: (yyyy-mm-dd)",
            fill="#000000",
            font=("YanoneKaffeesatz Regular", 17 * -1)
        )

        entry_image_3 = PhotoImage(
            master=canvas,
            name="ent3",
            file=self.relative_to_assets("entry_3.png"))
        entry_bg_3 = canvas.create_image(
            165.5,
            279.5,
            image=entry_image_3
        )
        entry_3 = Entry(
            bd=0,
            bg="#989A9E",
            fg="#000716",
            highlightthickness=0
        )
        entry_3.place(
            x=24.0,
            y=260.0,
            width=285.0,
            height=40.0
        )

        canvas.create_text(
            26.0,
            236.0,
            anchor="nw",
            text="Discard Date Of The Product: (yyyy-mm-dd)",
            fill="#000000",
            font=("YanoneKaffeesatz Regular", 16 * -1)
        )

        button_image_1 = PhotoImage(
            master=canvas,
            name="btn7",
            file=self.relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.add(entry_1.get(), entry_2.get(), entry_3.get()),
            relief="flat"
        )
        button_1.place(
            x=83.0,
            y=345.0,
            width=147.0,
            height=41.0
        )
        window.resizable(False, False)
        window.mainloop()

    def add(self, name: str, in_date: str, out_date: str):
        Main().add_product(name, in_date, out_date)

if __name__ == '__main__':
    a = AddProduct()
    a.run()
