
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from add_product_gui import AddProduct
from remove_product_gui import RemoveProduct
from add_to_storage_gui import AddToStorage
from remove_from_storage_gui import RemoveFromStorage
from list_of_products_gui import ListOfProducts
from storage_gui import Storage
from search_products_gui import SearchProducts
from search_storage_gui import SearchStorage

class Engine:
    def __init__(self):
        OUTPUT_PATH = Path(__file__).parent
        self.ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Martin\Desktop\Database\assets\frame0")


    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

    def run(self):
        window = Tk()

        window.geometry("431x588")
        window.configure(bg = "#141A29")

        image_image_2 = PhotoImage(
                    name="img2",
                    file=self.relative_to_assets('image_1.png'))

        canvas = Canvas(
            window,
            bg = "#141A29",
            height = 588,
            width = 431,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            master=canvas,
            name='img1',
            file=self.relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            215.0,
            333.0,
            image=image_image_1
        )

        canvas.create_text(
            15.0,
            15.0,
            anchor="nw",
            text="Storage Management System",
            fill="#FFFFFF",
            font=("Ramabhadra", 20 * -1)
        )

        button_image_1 = PhotoImage(
            master=canvas,
            name='btn1',
            file=self.relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: AddProduct().run(win=window),
            relief="flat"
        )
        button_1.place(
            x=15.0,
            y=90.0,
            width=196.0,
            height=152.0
        )

        button_image_2 = PhotoImage(
            master=canvas,
            name='btn2',
            file=self.relative_to_assets("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: RemoveProduct().run(win=window),
            relief="flat"
        )
        button_2.place(
            x=15.0,
            y=250.0,
            width=196.0,
            height=71.0
        )

        button_image_3 = PhotoImage(
            master=canvas,
            name='btn3',
            file=self.relative_to_assets("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: ListOfProducts().run(),
            relief="flat"
        )
        button_3.place(
            x=15.0,
            y=410.0,
            width=196.0,
            height=152.0
        )

        button_image_4 = PhotoImage(
            master=canvas,
            name='btn4',
            file=self.relative_to_assets("button_4.png"))
        button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: AddToStorage().run(win=window),
            relief="flat"
        )
        button_4.place(
            x=221.0,
            y=90.0,
            width=196.0,
            height=152.0
        )

        button_image_5 = PhotoImage(
            master=canvas,
            name='btn5',
            file=self.relative_to_assets("button_5.png"))
        button_5 = Button(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: RemoveFromStorage().run(win=window),
            relief="flat"
        )
        button_5.place(
            x=221.0,
            y=250.0,
            width=196.0,
            height=71.0
        )

        button_image_6 = PhotoImage(
            master=canvas,
            name='btn6',
            file=self.relative_to_assets("button_6.png"))
        button_6 = Button(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: Storage().run(),
            relief="flat"
        )
        button_6.place(
            x=221.0,
            y=410.0,
            width=196.0,
            height=152.0
        )
        button_image_7 = PhotoImage(
            file=self.relative_to_assets("button_7.png")
        )
        button_7 = Button(
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: SearchProducts().run(win=window),
            relief="flat"
        )
        button_7.place(
            x=15.0,
            y=329.0,
            width=196.0,
            height=68.0
        )

        button_image_8 = PhotoImage(
            file=self.relative_to_assets("button_8.png"),
        )
        button_8 = Button(
            image=button_image_8,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: SearchStorage().run(win=window),
            relief="flat"
        )
        button_8.place(
            x=221.0,
            y=326.0,
            width=196.0,
            height=71.149
        )

        window.resizable(False, False)
        window.mainloop()

if __name__ == '__main__':
    e = Engine()
    e.run()
